version: '3.3'
services:
  nginx_ssl:
    image: nginx
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ./nginx:/etc/nginx/conf.d
     - ./site:/var/www/html
    networks:
     - docker-network

  certbot:
    image: certbot/certbot
    volumes:
     - /etc/letsencrypt:/etc/letsencrypt
     - ./site:/var/www/html

    command: "renew
              --webroot
              --webroot-path=/var/www/html"

networks:
  docker-network:
    driver: bridge
